---
collections:
  - name: cloud.terraform
    type: git
    source: https://github.com/diademiemi/cloud.terraform.git
    version: main
  - name: diademiemi.utils
  - name: diademiemi.python
  - name: diademiemi.vm_utils
  - name: diademiemi.minecraft


...
