defaultNamespace: argocd
helm:
  releaseName: argo-cd
  chart: argo-cd
  repo: https://partner-charts.rancher.io/
  version: "5.53.8"

  values:
    server:
      config:
        kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

    repoServer:
      # Use init containers to configure custom tooling
      # https://argoproj.github.io/argo-cd/operator-manual/custom_tools/
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: sops-age-key
          secret:
            secretName: sops-age-key # Deployed in Ansible

      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.2.1
          command: ["/bin/sh", "-c"]
          args:
            - echo "Installing KSOPS...";
              mv ksops /custom-tools/;
              mv kustomize /custom-tools/;
              echo "Done.";
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      volumeMounts:
        - mountPath: /usr/local/bin/kustomize
          name: custom-tools
          subPath: kustomize
        - mountPath: /home/argocd/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
          name: custom-tools
          subPath: ksops
        - mountPath: /home/argocd/.config/sops/age
          name: sops-age-key
      env:
        - name: SOPS_AGE_KEY_FILE
          value: /home/argocd/.config/sops/age/keys.txt
        - name: XDG_CONFIG_HOME
          value: /home/argocd/.config
        - name: KUSTOMIZE_PLUGIN_HOME
          value: /home/argocd/.config/kustomize/plugin
