---
- name: Refresh apt cache
  tags: apt, cache, always
  hosts: foreman
  tasks:
    - name: Refresh apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

- name: Install Foreman
  tags: foreman, install, always
  ansible.builtin.import_playbook: 01-install.yml

- name: Install Foreman Proxy services
  tags: foreman, foreman-proxy, always
  ansible.builtin.import_playbook: 02-proxy.yml

- name: Configure Foreman
  tags: foreman, foreman-configure, always
  ansible.builtin.import_playbook: 03-configure.yml

...
