---
- name: Deploy MC server
  hosts: all
  vars:
    minecraft_server_dest: "{{ ansible_user_dir}}/purpur"
  tasks:
    - name: Update apt cache
      tags: apt
      ansible.builtin.apt:
        update_cache: true

    - name: Install pip
      tags: python
      ansible.builtin.include_role:
        name: diademiemi.python.pip
      vars:
        python_pip_global_packages:
          - name: bs4

    - name: Install java 17
      tags: java
      ansible.builtin.apt:
        name: openjdk-17-jre-headless
        state: present

    - name: Install a Purpur server
      tags: mc
      diademiemi.minecraft.server:
        path: "{{ minecraft_server_dest }}"
        type: purpur  # purpur/paper/spigot/vanilla
        version: 1.20.4  # Server version
        build: latest  # Build number, "latest" fetches the latest build
        java_opts: 'aikar'  # empty string defaults to just memory opts, "aikar" adds Aikar's flags, any other string adds that string to the flags
        min_memory: "4096"  # In MB
        max_memory: "8192"  # In MB
        plugins: "{{ _plugins | list + additional_plugins | default([]) | list }}"
          # - name: "Jar File Name"
          #   source: "https://example.com/path/to/jar.jar"
          #   type: url/bukkit/spigot/hangar
          #   version: "1234567"  # Only for bukkit/hangar, "latest" fetches the latest version
          #   state: present/absent/download  # Download forces redownload
      vars:
        _plugins:
          - name: EssentialsX
            source: https://ci.ender.zone/job/EssentialsX/1531/artifact/jars/EssentialsX-2.21.0-dev+24-0af4436.jar
            type: url  # Downloads straight from the URL
            state: present
          - name: Vault
            source: https://www.spigotmc.org/resources/vault.34315/
            type: spigot  # Does not support downloading specific versions
            state: present
          - name: WorldGuard
            source: https://dev.bukkit.org/projects/worldguard
            type: bukkit
            version: latest
            state: present
          - name: WorldEdit
            source: https://dev.bukkit.org/projects/worldedit
            type: bukkit
            version: latest
            state: present
          - name: ViaVersion
            source: https://www.spigotmc.org/resources/viaversion.19254/
            type: spigot
            state: present
          - name: LuckPerms
            source: https://www.spigotmc.org/resources/luckperms.28140/
            type: spigot
            state: present
          - name: Geyser
            source: https://download.geysermc.org/v2/projects/geyser/versions/2.2.2/builds/453/downloads/spigot
            type: url
            state: present
          - name: Floodgate
            source: https://download.geysermc.org/v2/projects/floodgate/versions/2.2.2/builds/96/downloads/spigot
            type: url
            state: present
          - name: DiscordSRV
            source: https://www.spigotmc.org/resources/discordsrv.18494/
            type: spigot
            state: present

    - name: Place configs
      ansible.builtin.template:
        src: "{{ item.src | default(item) }}.j2"
        dest: "{{ minecraft_server_dest }}/{{ item.dest | default(item) }}"
        mode: '0644'
      register: template_place
      changed_when: template_place is changed and not item.ignore_changes | default(false)
      loop:
        - src: server.properties
          dest: server.properties
          ignore_changes: true
        - src: eula.txt
          dest: eula.txt
          ignore_changes: true
        # - src: discordsrv.yml
        #   dest: plugins/DiscordSRV/config.yml

...
