---
collections:
  - name: cloud.terraform
    type: git
    source: https://github.com/diademiemi/cloud.terraform.git
  - name: freeipa.ansible_freeipa
  - name: middleware_automation.keycloak
  - name: diademiemi.utils
  - name: diademiemi.python
  - name: diademiemi.vm_utils

roles:
  - name: diademiemi.wireguard

...
